FROM rust:1.78-alpine

RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers

WORKDIR /workspace

RUN adduser -D -u 1000 runner && \
    chown -R runner:runner /workspace

USER runner

ENV PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV HOME=/tmp
ENV CARGO_HOME=/tmp/cargo
ENV RUSTUP_HOME=/tmp/rustup
