FROM node:20-alpine

WORKDIR /workspace

RUN adduser -D -u 1000 runner && \
    chown -R runner:runner /workspace

USER runner

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENV HOME=/tmp
ENV NODE_ENV=production
